### ISSUE TITLE
Brightness also changes when color is changed.

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.cloud#45]
The brightness always changes to 100% again, when color is changed.

Scenario:
1.) Swith hue lamp on
2.) Set level to 50%
3.) Change color to blue (or anything else)

Result:
Color is blue but brightness is also set to 100%.

![huelamp](https://user-images.githubusercontent.com/3912027/34654071-61f48eec-f3f6-11e7-8e5e-90f7cae34b4d.png)

**Comment by modmax** [comment]
The behaviour is due the hue implementation I think.

In the newiest version there is a fix to set
`"ignoreAlexaColor": "true"`
In the object common section of the hue lamp bri section.

This works but is not very intiuitive.
Perhaps this should be added in the cloud-section of the brightness state, when byON is set to "stored".
Or if "stored" is selected, then bri changes du color changes are ignored,

**Comment by WolfspiritM** [comment]
The implementation of hue in the cloud adapter seems to be right in my opinion.
The reason is that you can actually ask alexa to turn the light to "dark blue" which sends a brightness change: ```{"hue":240,"saturation":1,"brightness":0.3882}```
While setting color to blue looks like that: ```{"hue":240,"saturation":1,"brightness":1}```

We can't really ignore the brightness value in general.
Maybe we can use the stored brightness, but I'd like to hear other thoughts first.

Also I noticed that "dark blue" for example doesn't work or at least not always. The reason for that seems to be the hue adapter as if we set hue, sat and bri quickly after another then the hue adapter seems to get confused and overrides bri to the old value. If I add a timeout then bri is successfully applied. That's also why at some tests for me it didn't change brightness.

@GermanBluefox I think that might need some change in the hue adapter. Here is a sample script:
```
var hue = "hue.0.Philips_hue.Go";

setState(hue+".hue", 120, false, function() {
    setState(hue+".sat", 254, false, function() {
        setTimeout(function(){
            setState(hue+".bri", 110, false, function() {
                
            });
        },10);
    });
});
```
Change setState for bri between low and high values and sometimes it doesn't apply correctly.

Log file (Notice how the "val":10 for bri is correct but at the end sets the old value. Maybe hue should merge the input from stateChange to make sure it uses the most recent value?)
```

hue.0 | 2018-01-08 01:13:59.671 | info | final lightState for Philips_hue.Go:{"bri":210,"on":true,"level":83} requested at: 1515370439591
hue.0 | 2018-01-08 01:13:59.627 | info | final lightState for Philips_hue.Go:{"bri":10,"on":true,"hue":120,"sat":254,"colormode":"hs","level":4} requested at: 1515370439573
hue.0 | 2018-01-08 01:13:59.603 | info | final lightState for Philips_hue.Go:{"bri":210,"on":true,"hue":120,"sat":254,"colormode":"hs","level":83} requested at: 1515370439557
hue.0 | 2018-01-08 01:13:59.600 | debug | stateChange hue.0.Philips_hue.Go.bri {"val":10,"ack":false,"ts":1515370439591,"q":0,"from":"system.adapter.javascript.0","lc":1515370439591}
hue.0 | 2018-01-08 01:13:59.577 | debug | stateChange hue.0.Philips_hue.Go.sat {"val":254,"ack":false,"ts":1515370439573,"q":0,"from":"system.adapter.javascript.0","lc":1515369832457}
hue.0 | 2018-01-08 01:13:59.562 | debug | stateChange hue.0.Philips_hue.Go.hue {"val":120,"ack":false,"ts":1515370439557,"q":0,"from":"system.adapter.javascript.0","lc":1515370370126}
```

I fixed it by adding this line to the hue adapter:
https://gist.github.com/WolfspiritM/38a30ceee1ec98e02b7d2b49fb4d1d3d#file-hue-js-L60
Is that a good solution? This way it merges the value we got from stateChange with the values we got from adapter.getStates and makes sure we always use the changed value.

**Comment by AlCalzone** [comment]
Somehow this is broken for me too with tradfri. No matter what I enter here:
![unbenannt](https://user-images.githubusercontent.com/17641229/34848751-38b31300-f720-11e7-8dc4-93498fefcb6c.PNG)
saying "Alexa, turn XYZ on" results in both the brightness and the color temperature being set to 100%.
It used to work with one of the first version of 2.2.0. Now it doesn't. Any ideas @WolfspiritM?

**Comment by WolfspiritM** [comment]
I can't reproduce with a Tradfri connected to hue. Only thing I noticed is that for the "by On" value it seems to use 100 and doesn't map it to the max value (254).
Brightness should be a level.dimmer, right?
So it should find that and use that for percentage control.

Can you set debugging to info and see what it says when you switch the device?
For me it shows:
```
cloud.0 | 2018-01-11 23:45:42.114 | debug | Won't control hue.0.Philips_hue.Color_temperature_light_1.ct as we have a switch available.
cloud.0 | 2018-01-11 23:45:42.107 | debug | Set "hue.0.Philips_hue.Color_temperature_light_1.bri" to 100
cloud.0 | 2018-01-11 23:45:42.107 | debug | Controlling: hue.0.Philips_hue.Color_temperature_light_1.ct
cloud.0 | 2018-01-11 23:45:42.107 | debug | Controlling: hue.0.Philips_hue.Color_temperature_light_1.bri
cloud.0 | 2018-01-11 23:50:37.984 | debug | Won't control hue.0.Philips_hue.Color_temperature_light_1.ct as we have a dimmer available for this channel.
cloud.0 | 2018-01-11 23:50:37.984 | debug | Remember ON value for "hue.0.Philips_hue.Color_temperature_light_1.bri": 177.79999999999998
cloud.0 | 2018-01-11 23:50:37.984 | debug | Controlling hue.0.Philips_hue.Color_temperature_light_1.bri .
cloud.0 | 2018-01-11 23:50:37.961 | debug | Controlling percentage: hue.0.Philips_hue.Color_temperature_light_1.ct
cloud.0 | 2018-01-11 23:50:37.961 | debug | Controlling percentage: hue.0.Philips_hue.Color_temperature_light_1.bri


```

**Comment by AlCalzone** [comment]
> I can't reproduce with a Tradfri connected to hue. Only thing I noticed is that for the "by On" value it seems to use 100 and doesn't map it to the max value (254).

For tradfri that is fine, as I defined most values in 0-100%. But you're right, a setting of 100% should change the value to the max value.

> Brightness should be a level.dimmer, right? So it should find that and use that for percentage control.

Actually it's a `light.dimmer`, maybe that's the issue. Brightness is fine though. The problem is that colorTemperature also gets changed to 100% although its set to "last value" or "default" in the configuration.

**Comment by WolfspiritM** [comment]
Yes, that definitely is the reason. The hue adapter sets the brightness as a "level.dimmer". My code explicitly checks for a "level.dimmer" to be available to use for percentage. If none is available it will set all available numbers (including color temperature and all other numbers) as it doesn't know which one to use.

https://github.com/ioBroker/ioBroker.hue/blob/37ed3d18081c861786ae7ca20108911ef6f82af8/hue.js#L533

I could also check for "light.dimmer" but I think this should be changed either for hue or for tradfri to match otherwise this will always cause trouble in newer implementations.

**Comment by AlCalzone** [comment]
> I think this should be changed either for hue or for tradfri

I agree. I'll change it for tradfri. Not sure what `light.dimmer` is for though, as that is also mentioned in the documentation.

**Comment by AlCalzone** [comment]
Tradfri v1.0.5 now has `level.dimmer` and the combination with `colorTemperature` works again.

**Comment by Omega236** [comment]
I have already the problem, when i change the brightness it also changes the Hue and the saturation.

and i don't understand why, what do i wrong?

![rgbcolor](https://user-images.githubusercontent.com/25373047/35665086-df0b9b6e-0724-11e8-94fb-c930a069ed1f.PNG)

![rgbcloud](https://user-images.githubusercontent.com/25373047/35665090-e5442424-0724-11e8-862e-c32cf21f4d88.PNG)

**Comment by WolfspiritM** [comment]
Hm...the reason why this is happening is that the level.dimmer is in another channel then the hue and saturation. This way the Cloud Adapter doesn't know that the dimmer will actually control the device instead of the other number values and as it doesn't find a dimmer  for the channel it will revert back to setting everything.

I'm not quiet sure what the best way would be to solve this.
For Hue the channel is the "device" (e.g. Lightstrip) while for Homematic the channel seems to be just part of the device. Interesting that the channel that can set the color does not provide a way to set the brightness :/

**Comment by AlCalzone** [comment]
> For Hue the channel is the "device" (e.g. Lightstrip) while for Homematic the channel seems to be just part of the device. Interesting that the channel that can set the color does not provide a way to set the brightness :/

Are there no "devices" in the hue adapter? That seems wrong - the other adapters mostly group functions inside a device by channels.

**Comment by WolfspiritM** [comment]
> Are there no "devices" in the hue adapter
There are.
The device is the Hue Bridge.
That's technically right cause the device you physically talk to is the bridge not the light.
The bridge then has a channel that reaches the light.

**Comment by AlCalzone** [comment]
> The device is the Hue Bridge.
> That's technically right cause the device you physically talk to is the bridge not the light.

I disagree, as a user I don't care about the bridge/controller/gateway, I care about the devices connected to it:
* Zwave physically talks to the controller (GPIO board or USB stick), but the ioBroker devices are the devices connected to the controller
* EnOcean physically talks to the controller (USB stick), but the ioBroker devices are the devices talking to the controller
* Same goes for tradfri (which is very similar to hue), apparently Homematic and many other devices.

**Comment by WolfspiritM** [comment]
I get your point 😃 
I just said that technically it's correct as the device you talk to is the bridge which then has different channels to the lights. That was just an explanation why it might be implemented like that.

The ID for hue looks like that "hue.0.Philips_hue.Go.level", where hue.0 is the adapter instance, "Philips_hue" seems to be the bridge ("type": "device"), "Go" is the Light ("type": "channel") and "hue" is the state. I also don't see any reason why the bridge itself is in there at all as it always is just one device. It might be that the hue adapter was designed at first to support multiple Bridges with a single adapter.
@GermanBluefox Can you explain? What might be the impact to define the Lights as the device in Hue instead of a channel so we can filter roles per device?
I think that change would also mean to remove the bridge from the ID and introduce a "fake" channel similar to the Tradfri "lightbulb" implementation by @AlCalzone. But that would break all existing scripts for hue as the ID will change drastically.

I will open an issue in the hue repository...
